services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
        maps-pg:
          condition: service_healthy
    networks:
      - maps-network
    restart: on-failure

  migrate:
      image: migrate/migrate
      depends_on:
        maps-pg:
          condition: service_healthy
      volumes:
        - ./migrations:/migrations
      command:
        [ "-path", "/migrations", "-database",  "postgres://postgres:${POSTGRES_PASSWORD}@maps-db:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
      networks:
        - maps-network

  maps-pg:
    container_name: maps-db
    hostname: maps-db
    image: postgres:17
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db.sh:/docker-entrypoint-initdb.d/db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - maps-network

networks:
  maps-network: