FROM golang:1.23.4-alpine3.20 AS builder

RUN mkdir /app
ADD . /app
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/migration/main.go

FROM alpine:3.20

RUN mkdir /app

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/.env .

RUN mkdir /migrations
COPY --from=builder /app/migrations ./migrations

CMD ["./main"]